PHP8.1 compatibility
yusufkandemir/microdata-parser pull request #2
Opened 2022-02-25 01:15 UTC by eboye

## Description

I've bumped the php version to 8.1 and added some strict types

## Motivation and context

Future versions compatibility

## How has this been tested?

unit tests included in the project

## Screenshots (if appropriate)

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [ ] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [ ] I have added tests to cover my changes.
- [ ] If my change requires a change to the documentation, I have updated it accordingly.

2022-02-25 06:06 UTC, yusufkandemir requested changes
Looking great 👏 I requested some changes to improve clarity.

2022-02-25 06:06 UTC, yusufkandemir commented on src/MicrodataDOMDocument.php
> +    public function loadHTML($source, $options = 0): \DOMDocument|bool
Let's also do `use DOMDocument;` to match with other usage.

2022-02-25 06:06 UTC, yusufkandemir commented on src/MicrodataDOMDocument.php
> +    public function loadHTMLFile($filename, $options = 0): \DOMDocument|bool
Let's also do `use DOMDocument;` to match with other usage.

2022-02-25 06:06 UTC, yusufkandemir commented on src/MicrodataParser.php
> +     *@see \json_encode() to description of parameters and return values
Is there a reason for moving this? If yes, please make this change:
```suggestion
     * @see \json_encode() to description of parameters and return values
```

2022-02-25 06:06 UTC, yusufkandemir commented on tests/MicrodataParserTest.php
> +     */
This is redundant as you have already specified the return type.
```suggestion
```

2022-02-25 06:06 UTC, yusufkandemir commented on src/MicrodataDOMDocument.php
> +    /** @var DOMXPath */
This became redundant after statically typing the property.
```suggestion
```

2022-02-25 06:06 UTC, yusufkandemir commented on tests/MicrodataParserTest.php
> +    ])]
Let's use the DocBlock version as it feels more natural and lean, and is supported by many tools like phpstan, phan, psalm, etc. which means the community is agreed on this solution. [PHPStorm supports this syntax too](https://blog.jetbrains.com/phpstorm/2021/07/phpstorm-2021-2-release/#array_shapes_phpdoc_syntax_support).
The VSCode extension doesn't support it yet, but it will be a bonus when it gets supported: https://github.com/bmewburn/vscode-intelephense/issues/249

```suggestion
    /**
     * @return array{uri: string, source: false|string, result: false|string}
     */
```

2022-02-25 06:06 UTC, yusufkandemir commented on tests/MicrodataParserTest.php
> +    #[ArrayShape([
See my other comment about using the DocBlock variant.

2022-02-25 06:06 UTC, yusufkandemir commented on tests/MicrodataTest.php
> +class MicrodataTest extends TestCase
I think it was shorter and clearer before. As it's used once and is a really specific use case, I don't think it needs a separate use statement. But, it's not a problem either way. Do you have a specific reason for specifying a use statement?

2022-02-25 06:06 UTC, yusufkandemir commented on src/MicrodataDOMElement.php
> +     * @return array|bool
Type hints don't support false, but we can at least specify it in DocBlocks.

```suggestion
     * @return array|false
```

2022-02-25 06:06 UTC, yusufkandemir commented on src/MicrodataDOMElement.php
> +     * @return array|bool
Type hints don't support false, but we can at least specify it in DocBlocks.

```suggestion
     * @return array|false
```

2022-02-25 06:06 UTC, yusufkandemir commented on src/MicrodataParser.php
>      /** @var MicrodataDOMDocument */
This became redundant after statically typing the property.
```suggestion
```

2022-02-26 00:45 UTC, eboye commented
Sure, no specific reasons why I used those, just a matter of habit adding those :)

2022-02-26 17:02 UTC, yusufkandemir commented
@eboye did you forget to push your changes, or will you push them later? 🙂

2022-02-27 02:03 UTC, eboye commented
Sorry, here they are.

The only thing I want to mention is that this one test fails after my tinkering:

```
TypeError : PHPUnit\Framework\Assert::assertContains(): Argument #2 ($haystack) must be of type iterable, string given, called in ~/GitHub/microdata-parser/tests/MicrodataParserTest.php on line 82
~/GitHub/microdata-parser/tests/MicrodataParserTest.php:82
```

2022-04-01 23:23 UTC, merged

2022-04-03 15:50 UTC, yusufkandemir commented
@eboye thanks for the contributions! I made more changes, migrated to Pest from PHPUnit, migrated to GitHub actions from all other CI tools, and improved the code quality, then released https://github.com/yusufkandemir/microdata-parser/releases/tag/v1.0.0, enjoy!

2022-04-03 17:33 UTC, eboye commented
Great!